# Site Settings
title: Blog Betta
email: bettadevindonesia@gmail.com
description: >
  Ini adalah Blog Betta!
baseurl: "/blog" # Sesuaikan dengan root / nama folder
url: "http://127.0.0.1:4000" # Sesuaikan dengan nama url website
twitter_username: blogbetta
github_username:  blogbetta

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM