# Site Settings
title: Betta Dev Indonesia Education
email: bettadevindonesia@gmail.com
description: >
  Ini adalah Blog Betta Dev Indonesia Education!
baseurl: "" # Sesuaikan dengan root / nama folder
url: "" # Sesuaikan dengan nama url website
twitter_username: blogbetta
github_username:  blogbetta

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM